version: '3.4'

services:
  nestjsprisma:
    image: nestjsprisma
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 1m30s
      timeout: 40s
      retries: 5
      start_period: 30s
    
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: nestjsdb
      MYSQL_USER: nestjsuser
      MYSQL_PASSWORD: nestjspassword
    ports:
      - 3306:3306
